#!/bin/bash
#
#
#
#

export LANG=C
CNT_NAME=`hostname -s`

# fdisk -l
FN=fdisk_l.txt
LANG=C;fdisk -l > /tmp/$FN
./os_put.py /tmp/$FN $CNT_NAME $FN
rm -f /tmp/$FN

# df -m
FN=df_m.txt
LANG=C;df -m > /tmp/$FN
./os_put.py /tmp/$FN $CNT_NAME $FN
rm -f /tmp/$FN

# /boot/grub2/grub.cfg
FN=grub.cfg
./os_put.py /boot/grub2/$FN $CNT_NAME $FN

# /boot/grub2/device.map
FN=device.map
./os_put.py /boot/grub2/$FN $CNT_NAME $FN

# /etc/fstab
FN=fstab
./os_put.py /etc/$FN $CNT_NAME $FN

# /root/credentials.json
FN=credentials.json
./os_put.py /root/os_tools/$FN $CNT_NAME $FN

# BOOT 
DEVICE=sda1
printf "=== $DEVICE ===\n" > xfsdump.log
xfsdump -L $DEVICE -l 0 - /dev/$DEVICE 2>> xfsdump.log | ./os_dump.py $CNT_NAME $DEVICE

printf "\n" >> xfsdump.log
# ROOT
DEVICE=sda3
printf "=== $DEVICE ===\n" >> xfsdump.log
xfsdump -L $DEVICE -l 0 - /dev/$DEVICE 2>> xfsdump.log | ./os_dump.py $CNT_NAME $DEVICE

# xfsdump.log
FN=xfsdump.log
./os_put.py ./$FN $CNT_NAME $FN

grep "session " xfsdump.log



