#!/bin/bash

HOSTNAME=linux_backup

mkdir /sysimage
mkdir /sysimage/boot
mount -t xfs  /dev/sda3 /sysimage
mount -t xfs  /dev/sda1 /sysimage/boot

cd /sysimage
rm -fr *

ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $HOSTNAME sda3 | xfsrestore - /sysimage

cd /sysimage/boot
ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $HOSTNAME sda1 | xfsrestore - /sysimage/boot

ls -l /dev/disk/by-uuid/
cat /sysimage/etc/fstab
cat /sysimage/etc/default/grub

# vi /etc/fstab 
# grub2-mkconfig
# grub2-install --boot-directory /sysimage/boot /dev/sda
# sync
# sync
# reboot
#


