#!/bin/bash

HOSTNAME=

mkdir /sysimage
mkdir /sysimage/boot
mount -t ext4  /dev/sda3 /sysimage
mount -t ext2  /dev/sda1 /sysimage/boot
cd /sysimage
ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $HOSTNAME sda3 | restore -rf -

cd boot
ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $HOSTNAME sda1 | restore -rf -

ls -l /dev/disk/by-uuid/

cat /etc/fstab

cat /etc/grub.conf

#
# chroot /sysimage
# export PATH=/bin:/sbin:$PATH
# MAKEDEV sda
# grub
# grub> root (hd0,0)
# setup (hd0)
# quit
# sync

