#!/bin/bash

####################
CNT_NAME=
####################

./os_download.py $CNT_NAME OS.txt OS.txt

OS_DIST=`cat OS.txt`

if [ $OS_DIST = "CentOS" ]; then
    OS_RELEASE=centos-release
    ./os_download.py $CNT_NAME $OS_RELEASE $OS_RELEASE

    if [ -f $OS_RELEASE ]; then
	OS_VER=`cat $OS_RELEASE |sed -e 's/[^0-9.]//g'|awk '/^[0-9]/ { print int($1) }'`
    else 
	printf "Unknown OS\n"
	exit
    fi

else
    printf "Other Distribution\n"
    exit
fi

echo
echo $OS_DIST
echo $OS_VER
echo

######## CentOS common
mkdir /sysimage
mkdir /sysimage/boot


######## CentOS 6
if [ $OS_VER -eq 6 ];then

mount -t ext4  /dev/sda3 /sysimage
mount -t ext2  /dev/sda1 /sysimage/boot

cd /sysimage
rm -fr *

ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $CNT_NAME sda3 | restore -rf -

cd /sysimage/boot
ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $CNT_NAME sda1 | restore -rf -

ls -l /dev/disk/by-uuid/
cat /sysimage/etc/fstab
cat /sysimage/etc/grub.conf

# 
# vi /sysimage/etc/fstab
# vi /sysimage/etc/fstab
#
# chroot /sysimage
# export PATH=/bin:/sbin:$PATH
# MAKEDEV sda
# grub
# grub> root (hd0,0)
# setup (hd0)
# quit
# exit
# sync
# sync
# reboot
#


######## CentOS 7
elif [ $OS_VER -eq 7 ];then

mount -t xfs  /dev/sda3 /sysimage
mount -t xfs  /dev/sda1 /sysimage/boot

cd /sysimage
rm -fr *

ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $CNT_NAME sda3 | xfsrestore - /sysimage

cd /sysimage/boot
ln -s /root/os_tools/credentials.json .
/root/os_tools/os_restore.py $CNT_NAME sda1 | xfsrestore - /sysimage/boot

ls -l /dev/disk/by-uuid/
cat /sysimage/etc/fstab
cat /sysimage/etc/default/grub

# vi /etc/fstab 
# grub2-mkconfig
# grub2-install --boot-directory /sysimage/boot /dev/sda
# sync
# sync
# reboot
#


######## Other
else

printf "Abort! due to unknown OS"
exit

fi





